version: '3'

tasks:
  test:
    cmds:
    # Run all unit tests (fast)
    - uv run pytest tests/unit/ -v

  test-integration:
    cmds:
    # Run with real atlaslabs.weavemcp.app integration 
    - export WEAVE_TEST_TOKEN="your_token"
    - uv run pytest tests/integration/ -v

  test-all:
    cmds:
    # Use the test runner
    - python test_runner.py
